### =========================================================== ###
### localhost:8080/blogs
### Replace {:id} with the repective HexString UUID
### =========================================================== ###


###
### Should start with '{"message": "No blogs to display"}' or something similar, or with a collection of documents in the MongoDB collection
GET http://localhost:8080/blogs HTTP/1.1

###
### Each field has various validations attempted, and they send appropriate responses if failed. Fill them in as needed
POST http://localhost:8080/blogs HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "content": "",
    "title": "",
    "UUID": "",
    "date": ""
}

###
### Replace {:id} with the respective HexString UUID
GET http://localhost:8080/blogs/:id HTTP/1.1

###
### Replace {:id} with the respective HexString UUID
### Each field has various validations attempted, and they send appropriate responses if failed. Fill them in as needed
PUT http://localhost:8080/blogs/:id HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "content": "",
    "title": "",
    "UUID": "",
    "date": ""
}

###
### Each field has various validations attempted, and they send appropriate responses if failed. Fill them in as needed
POST http://localhost:8080/blogs HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "content": "",
    "title": "",
    "UUID": "",
    "date": ""
}

###
### Should return JSON with 2 items
GET http://localhost:8080/blogs HTTP/1.1

###
### Replace {:id} with the respective HexString UUID
GET http://localhost:8080/blogs/:id HTTP/1.1

###
### Replace {:id} with the respective HexString UUID
DELETE http://localhost:8080/blogs/:id HTTP/1.1

###
### Delete all documents within collection
DELETE http://localhost:8080/blogs HTTP/1.1

###
### Should end with '{"message": "No blogs to display"}' or something similar, or with a collection of documents in the MongoDB collection
GET http://localhost:8080/blogs HTTP/1.1


### =========================================================== ###
### Render - https://blogdata-3q6n.onrender.com/blogs
###

###
### Should start with '{"message": "No blogs to display"}' or something similar, or with a collection of documents in the MongoDB collection
GET https://blogdata-3q6n.onrender.com/blogs HTTP/1.1

###
### Each field has various validations attempted, and they send appropriate responses if failed. Fill them in as needed
POST https://blogdata-3q6n.onrender.com/blogs HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "content": "",
    "title": "",
    "UUID": "",
    "date": ""
}

###
### Replace {:id} with the respective HexString UUID
GET https://blogdata-3q6n.onrender.com/blogs/:id HTTP/1.1

###
### Replace {:id} with the respective HexString UUID
### Each field has various validations attempted, and they send appropriate responses if failed. Fill them in as needed
PUT https://blogdata-3q6n.onrender.com/blogs/:id HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "content": "",
    "title": "",
    "UUID": "",
    "date": ""
}

###
### Each field has various validations attempted, and they send appropriate responses if failed. Fill them in as needed
POST https://blogdata-3q6n.onrender.com/blogs HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "content": "",
    "title": "",
    "UUID": "",
    "date": ""
}

###
### Should return JSON with 2 items
GET https://blogdata-3q6n.onrender.com/blogs HTTP/1.1

###
### Replace {:id} with the respective HexString UUID
GET https://blogdata-3q6n.onrender.com/blogs/:id HTTP/1.1

###
### Replace {:id} with the respective HexString UUID
DELETE https://blogdata-3q6n.onrender.com/blogs/:id HTTP/1.1

###
### Delete all documents within collection
DELETE https://blogdata-3q6n.onrender.com/blogs/ HTTP/1.1

###
### Should start with '{"message": "No blogs to display"}' or something similar, or with a collection of documents in the MongoDB collection
GET https://blogdata-3q6n.onrender.com/blogs HTTP/1.1